<<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>AKS Academy</title>
        <style type="text/css">
            #backdrop 
            {
                height: 100%;
                left: 0;
                position: absolute;
                top: 0;
                width: 100%;
                background-color: #06A3DA;
            }
        </style>
</head>
<body id="backdrop">
</body>
</html>
<?php
    session_start();
    $con=mysqli_connect("localhost","root","","rsams_db")or die("Database Server Error");
//include('../../admin/code_part/connection.php');
    if(isset($_POST['submit']))
    {
        //$id=$_POST['id'];
        $uname=$_POST['name'];
        $gn=$_POST['gn'];
        $dob=$_POST['dob'];
        $photo=$_FILES['photo']['name'];
        $add=$_POST['address'];
        $mob=$_POST['mobile'];
        $email=$_POST['email'];
        $date = date('m/d/Y', time());
        $height=$_POST['height'];
        $weight=$_POST['weight'];
        $age=$_POST['age'];
        $gun_selection=$_POST['gun_selection'];
        $hand_selection=$_POST['hand_selection'];
        $fees=$_POST['amount'];
        $c_pass=$_POST['c_pass'];
        $pass=$_POST['pass'];
        //$status=$_POST['status'];
        $file_type=$_FILES['photo']['type'];
        $msg="";
        $file_upload=true;
        $msg="";
                       
         if(!($file_type=='image/jpeg' or $file_type=='image/png'))
         {
             $msg=$msg."Your Uploaded File Must Be Of JPEG Or PNG , Other File Types Are Not Allow";
             $file_upload=false;
         }
         $path="../upload/".$photo;

         if($file_upload==true)
         {
  $path1="upload/".$photo;

            
             if(move_uploaded_file($_FILES['photo']['tmp_name'],$path))
             {
                

                if ($pass==$c_pass) 
                {
    
                    $sql="INSERT INTO `tbl_registration` (`id`, `username`, `gender`, `dob`, `photo`, `address`, `phone_no`, `email`,`post_date`, `height`, `weight`, `age`, `gun_selection`, `hand_selection`, `fees`, `password`, `status`,`role`) VALUES (NULL, '$uname', '$gn', '$dob', '$path1', '$add', '$mob', '$email','$date', '$height', '$weight', '$age', '$gun_selection', '$hand_selection', '$fees', '$pass', '0','user');";


                    $qry=mysqli_query($con,$sql)or die("Query Error");
                    if($qry)
                    {
$_SESSION['gmail']=$email;
$_SESSION['fees']=$fees;
$_SESSION['mob']=$mob;

                        //echo "<script>alert('Record Insert Successfully');</script>";
                        $sql_buy="INSERT INTO `tbl_paymant` (`id`, `user_gmail`, `fees`, `buy_date`,`status`) VALUES (NULL, '$email', '$fees', current_timestamp(),'pending');";

                        $sql_run=mysqli_query($con,$sql_buy);

                        
                    }
                    else
                    {
                        echo "<script>alert('File Not Upload Successfully');</script>";
                    }

                }
            else
            {
                echo "<script>alert('Password and Confirm Password Must Not Match...');</script>";
            }
        }
        else
        {
            echo $msg;
        }
    }
}
?>

<?php

 $apiKey = "rzp_test_Wi972bG7df7ltY";

?>

<script src="https://code.jquery.com/jquery-3.5.0.js"></script>



<form action="../../admin/payment_view/payment_recipt.php?gmail=<?php echo $email; ?>" method="POST">
<script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="<?php echo $apiKey; ?>" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    data-amount="<?php echo $_POST['amount'] * 100;?>" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR"//You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-id="<?php echo 'OID'.rand(10,100).'END';?>"//Replace with the order_id generated by you in the backend.
    data-buttontext="CLICK ME TO DONATION"
    data-name="Shraddha Rananavare"
    data-description="DONATE!"
    data-prefill.name="<?php echo $_POST['name'];?>"
    data-prefill.email="<?php echo $_POST['email'];?>"
    data-prefill.contact="<?php echo $_POST['mobile'];?>"
    data-theme.color="#F37254"
></script>
<input type="hidden" custom="Hidden Element" name="hidden">
</form>

<style type="text/css">
    .razorpay-payment-button{
        display: none;
    }
</style>

<script type="text/javascript">
    $(document).ready(function(){
        $('.razorpay-payment-button').click();
    });
</script>